apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-regcred
  namespace: cl-christa-test
spec:
  encryptedData:
    .dockerconfigjson: AgB5nh6W0xUiEVYoh83Q37kJwtRSwL/i0U0v58J+TI7uc7lFaUSLIBW9nA8cutcxfr+9boX7VffW/sFGYZItkyan56axwCsSxZHfqtSrmGuQG5R8ecl4We5sVfGUfEmce1zApeli/F5axw5PUgwXW5bZOUmbzuaLc1iFa2rMCPmAEtpu/yrHbfEDO+kDCzqafg5ARZpYo6YvW0WFfxdcPL4VzSrZCqbWak7l3a5nFQylpbn8gD/n7tqOQCyKXeSNQciuZMKph2tUtQ+ZflYAU/ihMdE5WUnBfDGdHYr6K35zH6N0zba8mjuSYTYUnIrovcZdjSddQykDQ3ShotlEcfBE6fgjLxSyZlr8ToyyLCfHEszhqvPEs+kQRnjzFhg3NulSPCjN/uh45Q71tYbBH8kms/kYCnB2FqtB3K8zieIwdU7FwV/4TCAN9lBCH+6SxFEtBhPF30nyjCoGqIEg7BkldEEMz016sAD1TqZoMn7s4Xxy781qstbBKdzXsqLFCuKoRTjoBGw9V4fK+tKju1G8ZPEFaVee8AGEQZgkKLNou7/m/JQB8ZogQdQg4GXaIyqHhKAH+Roty7uWoxEAUrX908JRh5qOcxlX2tX4Sj8oZ6XTKZKuLLK2jJoUf6QzEktZ38QupZb6TlHEEcOMGRB4hE5Xm0EJ7n3dRQHZlPCs2poiFjs9VcjNMGn3LE34ZlzNhlPJaFb5KroVjRcAnj36o5sMvCPGykI+1HolB4gAzSGasU4SsrPec6pDh0QpjHYgcX+HR5ZqUI76BTb+e4oh8lBylJbdhzzTYmB70avTfvEU4iaHjvbDjBnqRmBcoeW794zc52brmQBN8nOwBtQyLP5hzm80S6ocQbyboeYk1zzWrRuLAj7BCdvDhqS+R74Zd/xq0/UgqPUSDZsf/jcidaPKswuLcwRL0qCF
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-regcred
      namespace: cl-christa-test
    type: kubernetes.io/dockerconfigjson