apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
  namespace: cl-christa-test
type: Opaque
stringData:
  jwt-secret: -- randomly generated string here ---
  database-password: -- db password here --
  gcp-service-account.json: --- Put GCP json here ---
  mailgun-api-key: Mailgun Key Here
  recaptcha-secret: Recaptcha Secret Here
