apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-nuxt
  labels:
    app: strapi
spec:
  selector:
    matchLabels:
      app: nuxt
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nuxt
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nuxt
          image: ghcr.io/excl-networks/christa-test/nuxt@sha256:replace-me
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: nuxt-local-strapi-url
                  name: strapi-config
            - name: STRAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: nuxt-public-strapi-url
                  name: strapi-config
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                configMapKeyRef:
                  key: recaptcha-site-key
                  name: strapi-config
