apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-api
  labels:
    app: strapi
spec:
  selector:
    matchLabels:
      app: strapi
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: strapi
        tier: backend
        track: stable
    spec:
      containers:
        - name: strapi
          image: ghcr.io/excl-networks/christa-test/strapi@sha256:replace-me
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 1337
          env:
            - name: STRAPI_HOST
              valueFrom:
                configMapKeyRef:
                  key: strapi-host
                  name: strapi-config
            - name: STRAPI_PORT
              valueFrom:
                configMapKeyRef:
                  key: strapi-port
                  name: strapi-config
            - name: STRAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: strapi-url
                  name: strapi-config
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: strapi-secrets
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: database-port
                  name: strapi-config
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: database-name
                  name: strapi-config
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: database-username
                  name: strapi-config
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: database-host
                  name: strapi-config
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: strapi-secrets
            - name: DATABASE_SSL
              valueFrom:
                configMapKeyRef:
                  key: database-ssl
                  name: strapi-config
            # GCS Values
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: gcs-bucket-name
                  name: strapi-config
            - name: GCS_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: gcp-service-account.json
                  name: strapi-secrets
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  key: recaptcha-secret
                  name: strapi-secrets
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: mailgun-domain
                  name: strapi-config
            - name: MAILGUN_HOST
              valueFrom:
                configMapKeyRef:
                  key: mailgun-host
                  name: strapi-config
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  key: mailgun-api-key
                  name: strapi-secrets
