name: 'Tests'

on:
  pull_request:
jobs:
  run-nuxt-lint:
    name: Run Nuxt Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./nuxt
        run: npm ci
      - name: Run Linter
        working-directory: ./nuxt
        run: npm run lint
  run-nuxt-build:
    name: Run Nuxt Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./nuxt
        run: npm ci
      - name: Run Build
        working-directory: ./nuxt
        run: npm run build
  run-express-lint:
    name: Run Strapi Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./strapi
        run: npm ci
      - name: Run Linter
        working-directory: ./strapi
        run: npm run build
